services:
  backend:
    build: ./backend
    container_name: financial_backend # <-- Имя для бэка
    restart: unless-stopped
    networks:
      - vs_code_default

  frontend:
    build: ./frontend
    container_name: financial_frontend # <-- Имя для фронта
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - vs_code_default

networks:
  vs_code_default:
    external: true